name: NiyazPusulasi
options:
  bundleIdPrefix: com.niyazpusulasi
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: C4WUTK99E3
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Adhan:
    url: https://github.com/batoulapps/adhan-swift.git
    from: "1.4.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios.git
    from: "5.0.0"

targets:
  NiyazPusulasi:
    type: application
    platform: iOS
    sources:
      - path: NiyazPusulasi
        excludes:
          - "**/.DS_Store"
    resources:
      - path: NiyazPusulasi/Resources/Assets.xcassets
      - path: NiyazPusulasi/Resources/cities_database.json
    info:
      path: NiyazPusulasi/Info.plist
    entitlements:
      path: NiyazPusulasi/NiyazPusulasi.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.niyazpusulasi.app
        INFOPLIST_FILE: NiyazPusulasi/Info.plist
        CODE_SIGN_ENTITLEMENTS: NiyazPusulasi/NiyazPusulasi.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Adhan
      - package: RevenueCat
      - target: NiyazPusulasWidget
        embed: true

  NiyazPusulasWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: NiyazPusulasWidget
        excludes:
          - "**/.DS_Store"
    info:
      path: NiyazPusulasWidget/Info.plist
    entitlements:
      path: NiyazPusulasWidget/NiyazPusulasWidget.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.niyazpusulasi.app.widget
        INFOPLIST_FILE: NiyazPusulasWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: NiyazPusulasWidget/NiyazPusulasWidget.entitlements
    dependencies:
      - package: Adhan

  NiyazPusulasTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NiyazPusulasTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: NiyazPusulasi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.niyazpusulasi.app.tests
