name: NiyazPusulasi
options:
  bundleIdPrefix: com.niyazpusulasi
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: C4WUTK99E3
    CODE_SIGN_STYLE: Manual
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Adhan:
    url: https://github.com/batoulapps/adhan-swift.git
    from: "1.4.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios.git
    from: "5.0.0"

targets:
  NiyazPusulasi:
    type: application
    platform: iOS
    sources:
      - path: NiyazPusulasi
        excludes:
          - "**/.DS_Store"
    resources:
      - path: NiyazPusulasi/Resources/Assets.xcassets
      - path: NiyazPusulasi/Resources/cities_database.json
    entitlements:
      path: NiyazPusulasi/NiyazPusulasi.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.niyazpusulasi.app
        PRODUCT_NAME: NiyazPusulasi
        INFOPLIST_FILE: NiyazPusulasi/Info.plist
        CODE_SIGN_ENTITLEMENTS: NiyazPusulasi/NiyazPusulasi.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.niyazpusulasi.app"
    dependencies:
      - package: Adhan
      - package: RevenueCat
      - target: NiyazPusulasWidget
        embed: true

  NiyazPusulasWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: NiyazPusulasWidget
        excludes:
          - "**/.DS_Store"
      - path: NiyazPusulasi/Models/WidgetPayload.swift
        buildPhase: sources
      - path: NiyazPusulasi/Models/PrayerTimeDay.swift
        buildPhase: sources
      - path: NiyazPusulasi/Models/PrayerName.swift
        buildPhase: sources
      - path: NiyazPusulasi/Extensions/String+Localization.swift
        buildPhase: sources
    entitlements:
      path: NiyazPusulasWidget/NiyazPusulasWidget.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.niyazpusulasi.app.widget
        PRODUCT_NAME: NiyazPusulasWidget
        INFOPLIST_FILE: NiyazPusulasWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: NiyazPusulasWidget/NiyazPusulasWidget.entitlements
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.niyazpusulasi.app.widget"
    dependencies:
      - package: Adhan

  NiyazPusulasTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NiyazPusulasTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: NiyazPusulasi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.niyazpusulasi.app.tests
        GENERATE_INFOPLIST_FILE: YES
